libupnpp.pc.in: fix static build
Static build of upmpdcli is broken since commit
45d75cb5ca31231fcbd15ae520959f73af762b63 because libutility dependency
is not retrieved from libupnpp.pc:

buildroot-linux-uclibc/sysroot/usr/lib -lmicrohttpd -L/home/buildroot/autobuild/instance-3/output-1/host/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib -lexpat -lpthread -L/home/buildroot/autobuild/instance-3/output-1/host/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib -lssl -lcrypto -latomic -lpthread -lz -lssl -lcrypto -lz -latomic -lpthread -lcrypto -lz -latomic -lpthread -lz -L/home/buildroot/autobuild/instance-3/output-1/host/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib -lz -latomic -lpthread -L/home/buildroot/autobuild/instance-3/output-1/host/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib -lexpat -lcurl -lssl -lcrypto -latomic -lpthread -lz -lssl -lcrypto -lz -latomic -lpthread -lcrypto -lz -latomic -lpthread -lz -lssl -L/home/buildroot/autobuild/instance-3/output-1/host/bin/../mips64el-buildroot-linux-uclibc/sysroot/usr/lib -lz -latomic -lpthread -lcrypto -lz -latomic -lpthread
/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/mips64el-buildroot-linux-uclibc/5.5.0/../../../../mips64el-buildroot-linux-uclibc/bin/ld: scctl_src/scctl.o: in function `tryserver(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/buildroot/autobuild/instance-3/output-1/build/upmpdcli-1.5.5/scctl_src/scctl.cpp:383: undefined reference to `Logger::getTheLog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Fix this build failure by adding -lutility to Libs.Private in
libupnpp.pc and by installing libutility.a

Fixes:
 - http://autobuild.buildroot.org/results/dfcf2c425fff0261551ea9a635865fc4f0d6b9cf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>